name: Rust dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3    
      with:
        name: pet-the-cat-gui_artifact
        path: /home/runner/work/pet_the_cat_gui/pet_the_cat_gui/target/debug/pet_the_cat_gui

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: pet-the-cat-gui_artifact
    - name: Test artifact download
      run: ls -R

